In [12]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import ClusterCentroids
from imblearn.combine import SMOTEENN
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.ensemble import BalancedRandomForestClassifier

# Read the CSV and Perform Basic Data Cleaning

In [6]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data

df = pd.read_csv('loanstats.csv', skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [7]:
# Create our features
 # YOUR CODE HERE
# Create our target
# YOUR CODE HERE
X =pd.get_dummies(df.drop(columns=["loan_status"]).copy())
y =df.loan_status

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [10]:
# Check the balance of our target values
df['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [13]:
# Split the X and y into X_train, X_test, y_train, y_test
# YOUR CODE HERE
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1,stratify=y)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [14]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [15]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE
X_scaler=scaler.fit(X_train)

In [16]:
# Scale the training and testing data
# YOUR CODE HERE
X_train_scaled=X_scaler.transform(X_train)
X_test_scaled=X_scaler.transform(X_test)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [19]:
# Resample the training data with the BalancedRandomForestClassifier
# YOUR CODE HERE
model = BalancedRandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini', 
                max_depth=None, max_features='auto',
                max_leaf_nodes=None, min_impurity_decrease=0.0,
                min_samples_leaf=2, min_samples_split=2,
                min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
                oob_score=False, random_state=1, replacement=False,
                sampling_strategy='auto', verbose=0, warm_start=False)
model.fit(X_train_scaled, y_train)

BalancedRandomForestClassifier(min_samples_leaf=2, n_jobs=1, random_state=1)

In [21]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_pred =model.predict(X_test_scaled)
bal =balanced_accuracy_score(y_test,y_pred)
bal

0.7368421052631579

In [22]:
# Display the confusion matrix
# YOUR CODE HERE
conf =confusion_matrix(y_test,y_pred)
conf

array([[14,  5],
       [ 0,  0]], dtype=int64)

In [13]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test,y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.67      0.90      0.07      0.78      0.59       101
   low_risk       1.00      0.90      0.67      0.95      0.78      0.62     17104

avg / total       0.99      0.90      0.67      0.94      0.78      0.62     17205

In [23]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE
data = model.feature_importances_
index = np.argsort(data)[::-1]
for i in range(X.shape[1]):
    print(f"{X.columns.values[i]}: ({data[index[i]]})")

loan_amnt: (0.07877202950840266)
int_rate: (0.07144913584773967)
installment: (0.06381899773137331)
annual_inc: (0.06266644042659789)
dti: (0.0554369621601965)
delinq_2yrs: (0.027135243908617497)
inq_last_6mths: (0.025196828883890677)
open_acc: (0.020021142584880348)
pub_rec: (0.018568572572936325)
revol_bal: (0.018071523284949972)
total_acc: (0.017011560477134726)
out_prncp: (0.016472405218045952)
out_prncp_inv: (0.014734254492155437)
total_pymnt: (0.014633098746989861)
total_pymnt_inv: (0.014585020135909869)
total_rec_prncp: (0.014420259978527005)
total_rec_int: (0.014262687516402806)
total_rec_late_fee: (0.014058253385335905)
recoveries: (0.014006488693682156)
collection_recovery_fee: (0.01392489477314197)
last_pymnt_amnt: (0.013585338188142504)
collections_12_mths_ex_med: (0.013514545529432249)
policy_code: (0.013275119185818222)
acc_now_delinq: (0.012950037476179243)
tot_coll_amt: (0.012924808249904425)
tot_cur_bal: (0.012864542961726254)
open_acc_6m: (0.012824598826298687)
open_act_il: (0.012278413686523907)
open_il_12m: (0.012270889934614615)
open_il_24m: (0.01210339092641756)
mths_since_rcnt_il: (0.011865430329827334)
total_bal_il: (0.011036069467590497)
il_util: (0.010803835505147526)
open_rv_12m: (0.010477716588718105)
open_rv_24m: (0.00954192166534202)
max_bal_bc: (0.009486860442590665)
all_util: (0.009374806315029863)
total_rev_hi_lim: (0.009007170625387442)
inq_fi: (0.008869373166593664)
total_cu_tl: (0.008719336280352024)
inq_last_12m: (0.008715325217151581)
acc_open_past_24mths: (0.008629288834759892)
avg_cur_bal: (0.008606538731139597)
bc_open_to_buy: (0.008370416458654294)
bc_util: (0.008235286764621796)
chargeoff_within_12_mths: (0.00823077270311198)
delinq_amnt: (0.007175845224077149)
mo_sin_old_il_acct: (0.006965649976292104)
mo_sin_old_rev_tl_op: (0.00696476996081228)
mo_sin_rcnt_rev_tl_op: (0.006562020354909922)
mo_sin_rcnt_tl: (0.006528514247573463)
mort_acc: (0.006461711673658737)
mths_since_recent_bc: (0.006095163725087308)
mths_since_recent_inq: (0.00602627469172754)
num_accts_ever_120_pd: (0.005854302858243649)
num_actv_bc_tl: (0.005820994644995927)
num_actv_rev_tl: (0.005707676074492042)
num_bc_sats: (0.005235398706543203)
num_bc_tl: (0.004851975312403449)
num_il_tl: (0.004667325155360322)
num_op_rev_tl: (0.004601639704464403)
num_rev_accts: (0.004567901830118061)
num_rev_tl_bal_gt_0: (0.004522814604236316)
num_sats: (0.0039192808278650645)
num_tl_120dpd_2m: (0.0038006124517458856)
num_tl_30dpd: (0.0034299888679252587)
num_tl_90g_dpd_24m: (0.003008864402164445)
num_tl_op_past_12m: (0.0022125677992270963)
pct_tl_nvr_dlq: (0.002033421317151159)
percent_bc_gt_75: (0.0019386386507768963)
pub_rec_bankruptcies: (0.0019294408585367176)
tax_liens: (0.001741016453808847)
tot_hi_cred_lim: (0.0015365022905796067)
total_bal_ex_mort: (0.001377150805831449)
total_bc_limit: (0.0012464264306477951)
total_il_high_credit_limit: (0.0012044919895007184)
home_ownership_ANY: (0.001008286409129129)
home_ownership_MORTGAGE: (0.000866512792725245)
home_ownership_OWN: (0.0008388934218612437)
home_ownership_RENT: (0.0007015340487934624)
verification_status_Not Verified: (0.0006898806275604494)
verification_status_Source Verified: (7.459152899050416e-05)
verification_status_Verified: (2.4284892196675057e-05)
issue_d_Feb-2019: (0.0)
issue_d_Jan-2019: (0.0)
issue_d_Mar-2019: (0.0)
pymnt_plan_n: (0.0)
initial_list_status_f: (0.0)
initial_list_status_w: (0.0)
next_pymnt_d_Apr-2019: (0.0)
next_pymnt_d_May-2019: (0.0)
application_type_Individual: (0.0)
application_type_Joint App: (0.0)
hardship_flag_N: (0.0)
debt_settlement_flag_N: (0.0)

### Easy Ensemble Classifier

In [25]:
# Train the EasyEnsembleClassifier
# YOUR CODE HERE
model_easy= EasyEnsembleClassifier(base_estimator=None, n_estimators=100, n_jobs=1,
            random_state=1, replacement=False, sampling_strategy='auto',
            verbose=0, warm_start=False)
model_easy.fit(X_train_scaled, y_train)

EasyEnsembleClassifier(n_estimators=100, n_jobs=1, random_state=1)

In [26]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_pred_two =model_easy.predict(X_test_scaled)
bal_two=balanced_accuracy_score(y_test,y_pred_two)
bal_two

NameError: name 'y_pred2' is not defined

In [17]:
# Display the confusion matrix
# YOUR CODE HERE

array([[   93,     8],
       [  983, 16121]])

In [18]:
# Print the imbalanced classification report
# YOUR CODE HERE

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205